apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: gosi
  name: gosi
  namespace: default
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: gosi
    spec:
      sourceRef:
        kind: DataSource
        name: rhel9 
        namespace: openshift-virtualization-os-images
      storage:
        resources:
          requests:
            storage: 1Gi
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: gosi
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
          rng: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        resources:
          requests:
            memory: 1Gi
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: gosi
        name: rootdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: admin
            password: 'redhatocp' 
            chpasswd: { expire: False }
        name: cloudinitdisk
